### ISSUE TITLE
Cant access settings page from navbar

### ISSUE THREAD

**Issue by advay-c** [Abdifatah-Abdi/Chatify#28]
Cant access settings page from navbar

**Comment by Abdifatah-Abdi** [comment]
In order to access the settings page from the navigation bar, you'd need to first, have a user id.
There are a few ways to have a user id, like assigning yourself one from debug.html.

Once you assign yourself an id, you should be able to access the settings.
Understandably, there isn't any visuals to signify whether you're signed in or not, but this should be fixed in the next few commits.

**Comment by Abdifatah-Abdi** [comment]
Fixed in 98e6dea2f43cf78edc7ceca5c6053de9a8700452
